import type { Metadata } from "next";
import { Ubuntu as SansFont } from "next/font/google";
import "./globals.css";
import { Provider } from "jotai";

const sansFont = SansFont({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sansFont.variable} font-sans antialiased bg-page-background flex flex-col md:p-4`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
